spring:
  datasource:
    type: com.zaxxer.hikari.HikariDataSource
    url: jdbc:mysql://localhost:3306/fasto
    username: root
    password:
    hikari:
      auto-commit: false
      pool-name: hikari
  liquibase:
    change-log: classpath:config/liquibase/master.xml
  mail:
    host: smtp.gmail.com
    port: 587
    username: anhkhoalegia3@gmail.com
    password: henzxqozqubxynlj
    properties.mail.smtp:
      auth: true
      starttls.enable: true
      ssl.trust: smtp.gmail.com